//navbar
import navbar from "/component/navbar.js";
document.getElementById("navbar").innerHTML=navbar();

//sidebar
import side from "/component/side.js"
document.getElementById("side").innerHTML=side();

//top_news
import top from "/component/top.js"
document.getElementById("top_news").innerHTML=top();

import ufooter from "/component/footer.js";
document.getElementById("ufooter").innerHTML=ufooter()

//slideshow
let para = [
    "India’s wholesale inflation surges to record high of 15.88 % in May 2022",
    "Appointment of India’s new CDS will be made soon: Rajnath Singh",
    "Adhir Ranjan Chowdhury, KC Venugopal detained as Congress protests Rahul Gandhi’s ED question",
    "Nitish Kumar in race to become next President of India? Nihar CM responds to rumours"
  ];

  let i = 0;

  let slideshow= document.querySelector("#slideshow");
  setInterval(function () {
    if(i>=para.length)
    {
      i=0
    }
    slideshow.innerHTML=null
    let p=document.createElement("p")
    p.innerText=para[i]
    slideshow.append(p)
    i++

  },2000);


let explainers_data = [
    {
        heading: "DNA Explainer: What is the digital Vidhan Sabha system and how it will function?",
        title: "DNA Explainer: What is the digital Vidhan Sabha system and how it will function?",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/06/14/2303726-national-e-vidhan-application-mpaindia.jpg",
        description: "National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "Why is the crypto market crashing today? Bitcoin and Ethereum now worth half of their all-time highs",
        title: "Why is the crypto market crashing today? Bitcoin and Ethereum now worth half of their all-time highs",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/06/13/2284209-crypto-crash-reuters.jpg",
        description: "What appears to be the immediate trigger for this crypto crash is a massive sell-off by investors amid heightened inflation fears.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: Why vote value of MPs will decrease in Presidential Election 2022",
        title: "DNA Explainer: Why vote value of MPs will decrease in Presidential Election 2022",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/06/15/2322450-presidential-election-ians.jpg",
        description: "This time the value of the vote of a Member of Parliament is likely to go down to 700 from 708 in the Presidential polls scheduled in July.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: How next-generation indigenously built Corvettes will help modernise Indian Navy",
        title: "DNA Explainer: How next-generation indigenously built Corvettes will help modernise Indian Navy",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/06/09/2207722-corvette-ani.jpg",
        description: "The length of Corvettes ships will not be longer than 120 metres. The crew of the new ships will consist of 21 officers and 137 sailors.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: What is Viagra overdose which leads to the condition priapism",
        title: "DNA Explainer: What is Viagra overdose which leads to the condition priapism",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/06/08/2186389-viagra-pixabay.jpg",
        description: "Viagra is regarded to be a safe drug to take as recommended by doctor. But if a person takes too much of Viagra, he may develop several side effects.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: What is ethanol blended petrol, how useful or harmful it is for vehicles",
        title: "DNA Explainer: What is ethanol blended petrol, how useful or harmful it is for vehicles",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/06/08/2183851-ethanol-blended-petrol-moefcc.jpg",
        description: "Ethanol, made from biomass, contains oxygen which helps in more complete combustion of the fuel, reduces emissions and is better for the environment.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: Why Gulf matters to India? How much are we inter-dependent",
        title: "DNA Explainer: Why Gulf matters to India? How much are we inter-dependent",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/06/08/2171113-india-gulf-rulers.jpg",
        description: "Relation between India and the Gulf has remained strong through decades. It is not only based on trade and commerce but also on history and culture.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: How Gujarat turned the game around for India in exporting French fries",
        title: "DNA Explainer: How Gujarat turned the game around for India in exporting French fries",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/06/06/2062611-gujarat-french-fries-ani.jpg",
        description: "Gujarat has processing plants of three companies - McCain Foods, Iscon Balaji Foods, HyFun Foods which produce frozen potato products and export them.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: Why has Turkey changed its name to Türkiye?",
        title: "DNA Explainer: Why has Turkey changed its name to Türkiye?",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/06/03/2120320-turkey-reuters.jpg",
        description: "While the names Turkey and Türkiye are pronounced similarly, the latter features a third syllable, which is pronounced something like 'yay'.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: Why Turkey rejected India's wheat consignment?",
        title: "DNA Explainer: Why Turkey rejected India's wheat consignment?",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/06/02/2098889-wheat-reuters.jpg",
        description: "As per reports, a Turkish trader said that Rubella virus was found in Indian wheat, due to which the Agriculture Ministry returned the consignment.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: Understanding two strains and four stages of monkeypox",
        title: "DNA Explainer: Understanding two strains and four stages of monkeypox",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/05/30/2042776-monkeypox-ians-hindi.jpg",
        description: "Monkeypox starts with fever, then general body aches, malaise and muscle aches. The first symptoms are similar to influenza.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: What has led to India's curb on sugar exports, what it means",
        title: "DNA Explainer: What has led to India's curb on sugar exports, what it means",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/05/27/2012256-india-sugar-export-reuters.jpg",
        description: "Unlike wheat, there is no complete ban on sugar export. But from June 1, traders have to secure permission for sale overseas.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "Gun violence top killer of American kids surpassing road accidents, drug overdose: Study",
        title: "Gun violence top killer of American kids surpassing road accidents, drug overdose: Study",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/05/26/1993801-pjimage.jpg",
        description: "The 4,300 firearm deaths among children and adolescents included homicides, suicides and unintentional deaths.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: Causes behind sudden rise in pediatric Hepatitis cases, what we know so far",
        title: "DNA Explainer: Causes behind sudden rise in pediatric Hepatitis cases, what we know so far",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/05/25/1977614-hepatitis-children-ians.jpg",
        description: "Hepatitis refers to an inflammatory condition of the liver. It is commonly the result of a viral infection, but there are other possible causes of it.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: How Russia's Terminator tank support system can be a game changer in Ukraine war",
        title: "DNA Explainer: How Russia's Terminator tank support system can be a game changer in Ukraine war",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/05/24/1960784-terminator-tank-support-system-israelmidru.jpg",
        description: "The Terminator tank support vehicle is heavily armored and designed to defend tanks from ambushes and attacks at close range in urban settings.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: Why summers spark off more vehicle fire incidents, causes and prevention",
        title: "DNA Explainer: Why summers spark off more vehicle fire incidents, causes and prevention",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/05/19/1904100-car-fire-reuters.jpg",
        description: "There are several reasons for the increase in fire incidents in summer months and most of them can be directly linked to the rise in temperature.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "DNA Explainer: What is weight loss surgery during which an actress lost her life",
        title: "DNA Explainer: What is weight loss surgery during which an actress lost her life",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/05/19/1889838-chethana-twitter.jpg",
        description: "Liposuction improves overall appearance of the body. It helps give the body a proper curve by smoothening it. Bariatric surgery is for weight loss.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    },

    {
        heading: "How a Saudi woman activist's iPhone revealed Pegasus snooping",
        title: "How a Saudi woman activist's iPhone revealed Pegasus snooping",
        image: "https://cdn.dnaindia.com/sites/default/files/styles/full/public/2022/05/20/1917083-saudi-activist-reuters.jpg",
        description: "Citizen Lab and Saudi activist Loujain al-Hathloul's find provided the basis for Apple's November 2021 lawsuit against NSO spyware company.",
        full_description: "The digital Vidhan Sabha system will help in streamlining information related to various state assemblies and eliminate the use of paper in day-to-day functioning. By doing so, several thousand tons of papers would be saved, which in turn would help in saving lakhs of trees annually.Through NeVA, the idea is to bring far reaching transformation in the governance across the country by making the people well informed and enlighten citizens and thereby strengthening the roots of the democracy in the country.NeVA will bring greater synergy, coordination, transparency and accountability between the legislature and the executive in a state and also across all the states in the country. Himachal Pradesh's Legislative Assembly implemented the pilot project of NeVA in 2014, where touch-screen devices replaced paper at the tables of the MLAs.Maximum use of Artificial intelligence (AI) and internet of things (IoT) infrastructure has been used to make National e-Vidhan Application (NeVA) a robust IT product.Besides, the e-Vidhan system has already been implemented in Kerala and Himachal Pradesh too. This year, Nagaland became the first state to implement NeVA, in March, 2022. This was possible through the National e-Vidhan Application (NeVA).The National e-Vidhan Application (NeVA) is a system for digitising the legislative bodies of all Indian states and the Parliament through a single platform on which house proceedings, starred/unstarred questions and answers, committee reports among others will be available.What is the National e-Vidhan Application (NeVA) system?NeVA or National e-Vidhan Application is a Unicode compliant software developed to make all the work and data related to legislative bodies available online for the use of both citizens and the members of Assemblies. NeVA includes a website and a mobile app.Through this software there is a providion for easy access to various documents like List of Questions, List of Business, Reports among others. This lives to the idea of 'One Nation, One Application' with the objective of Cloud First and Mobile First to serve Members' FIRST."
    }
]
displayData(explainers_data);

function displayData(data) {
    data.forEach(function (ele) {

        let bmain_box = document.createElement("div");
        bmain_box.setAttribute("id", "bmain_box");

        let bbox = document.createElement("div");
        bbox.setAttribute("id","bbox");

        let bimg_div = document.createElement("div");
        bimg_div.setAttribute("id", "bimg_div");

        let bimg = document.createElement("img");
        bimg.setAttribute("id", "bimg");

        let bpara = document.createElement("h3");
        bpara.setAttribute("id", "bpara");
        bpara.innerText = ele.title;
        bimg.src = ele.image;

        bpara.addEventListener("click",getNews)
        function getNews(){
            localStorage.setItem("newsByClick",JSON.stringify(ele))
            window.location.href = "./news_details.html"
        }

        bimg_div.append(bimg);
        bbox.append(bpara);
        bmain_box.append(bimg_div,bbox);

        document.querySelector("#news").append(bmain_box);

    });
}









